# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MainProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MainProject
source 'https://github.com/CocoaPods/Specs.git'  # 官方库
source 'https://gitee.com/ZhangLeYi/mySpecRepo.git'   # 私有库
source 'git@192.168.20.14:/home/wanbu/wanbu2.0/ios/APP/moduleTest/ZZeActionE.git' #万步服务器上的库

pod 'ZZeActionA','0.0.3'
pod 'ZZeActionB','0.0.17'
pod 'ZZeActionC','0.0.25'
pod 'FMDB','2.7.2'

pod 'ZZeActionF','0.0.2',source:'https://gitee.com/ZhangLeYi/ZZeActionF.git'
pod 'ZZeActionE','0.0.1',source:'git@192.168.20.14:/home/wanbu/wanbu2.0/ios/APP/moduleTest/ZZeActionE.git'

end
